---
- name: Run 'oc get pods' in OpenShift
  hosts: localhost
  gather_facts: no

  vars:
    namespace: default   # Change this to your desired namespace

  tasks:
    - name: Get pods using oc command
      command: oc get pods -n {{ namespace }}
      register: pod_output

    - name: Show raw output
      debug:
        var: pod_output.stdout_lines

