---
- name: Run 'oc get pods' in OpenShift
  hosts: localhost
  gather_facts: no

  vars:
    namespace: default   # Change this to your desired namespace

  tasks:

    - name: 
      command: oc login -u kubeadmin -p yDS7q-tYP4Q-UJpwq-4Zcas https://api.dcompsgai.dcom-psg-lab.xyz:6443 --insecure-skip-tls-verify
    - name: Get pods using oc command
      command: oc get pods -n {{ namespace }}
      register: pod_output

    - name: Pause for 20 seconds
      pause:
        seconds: 15  

    - name: Show raw output
      debug:
        var: pod_output.stdout_lines

