---
- name: Update environment variables and roll out latest deployment on OpenShift
  hosts: all
  connection: ssh
  tasks:
    - name: Login to OpenShift cluster
      command: oc login -u admin -p openshift https://api.cluster-xjp9c.xjp9c.sandbox1854.opentlc.com:6443
      
    - name: Set environment variable for deployment config
      command: oc set env dc/easytravel-loadgen ET_PROBLEMS- -n easytravel
      
    - name: Roll out latest deployment for easytravel-backend
      command: oc rollout latest dc/easytravel-backend -n easytravel
      
    - name: Roll out latest deployment for easytravel-frontend
      command: oc rollout latest dc/easytravel-frontend -n easytravel

    - name: Wait for 30 seconds
      pause:
        seconds: 30

    
