---
- name: Scale EasyTravel www deployment Up
  hosts: all
  connection: ssh
  gather_facts: no
  tasks:
  
    - name: Login to OpenShift cluster
      command: oc login -u admin -p openshift https://api.cluster-xjp9c.xjp9c.sandbox1854.opentlc.com:6443
     
    - name: Scale up easytravel-www in Openshift
      ansible.builtin.command: oc scale dc easytravel-www -n easytravel --replicas=1
      
    - name: Notify Slack channel
      slack:
       token: "T0508SWKB2N/B04V8C4P6A3/fr3b7rtyxJrZgjuRqQ1UCT1d"
       channel: "#devops"
       msg: "*Processing remediation Workflow. Application connectivity has been restored*"  
      
